Slightly bump NullRunner.test_timeout_no_output treshold again
It still caused a failure on ci.debian.net:

  AssertionError: 8.26797366142273 not less than 8